# Generated by Django 5.2.8 on 2025-11-10 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='カテゴリー名')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL用スラッグ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリー',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL用スラッグ')),
                ('excerpt', models.TextField(help_text='記事の概要を500文字以内で入力してください', max_length=500, verbose_name='要約・抜粋')),
                ('content', models.TextField(verbose_name='本文')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news_images/%Y/%m/', verbose_name='アイキャッチ画像')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('published', '公開'), ('archived', 'アーカイブ')], default='draft', max_length=20, verbose_name='ステータス')),
                ('is_featured', models.BooleanField(default=False, help_text='チェックすると注目記事として表示されます', verbose_name='注目記事')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('meta_title', models.CharField(blank=True, help_text='検索エンジン向けタイトル（60文字以内）', max_length=60, verbose_name='SEOタイトル')),
                ('meta_description', models.CharField(blank=True, help_text='検索エンジン向け説明文（160文字以内）', max_length=160, verbose_name='SEO説明文')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.category', verbose_name='カテゴリー')),
            ],
            options={
                'verbose_name': '記事',
                'verbose_name_plural': '記事',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='news_articl_status_f1b279_idx'), models.Index(fields=['category', 'status'], name='news_articl_categor_846014_idx'), models.Index(fields=['slug'], name='news_articl_slug_869c04_idx')],
            },
        ),
    ]
