# Generated by Django 5.2.8 on 2025-11-05 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='お名前を入力してください', max_length=100, verbose_name='お名前')),
                ('email', models.EmailField(help_text='メールアドレスを入力してください', max_length=254, verbose_name='メールアドレス')),
                ('message', models.TextField(help_text='お問い合わせ内容を入力してください', verbose_name='お問い合わせ内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('is_replied', models.BooleanField(default=False, help_text='返信が完了した場合にチェックしてください', verbose_name='返信済み')),
            ],
            options={
                'verbose_name': 'お問い合わせ',
                'verbose_name_plural': 'お問い合わせ一覧',
                'ordering': ['-created_at'],
            },
        ),
    ]
